name: Create Tag/Release
run-name: ${{ github.actor }} run build on ${{ github.repository }}
on:
  workflow_dispatch:
jobs:
    create-release:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-node@v3
        - run: git config user.name "$GITHUB_ACTOR"
        - run: version=$(npm version patch)
        - run: echo $version
        - run: git branch "releases/$version"
        - run: git push --all
        - run: git push --tags
      
        
