name: Create Release
run-name: ${{ github.actor }} run build on ${{ github.repository }}
on:
  workflow_dispatch:
jobs:
    create-release:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-node@v3
        - run: |
            git config user.name "GitHub Actions"
            git config user.email "actions@github.com"
        - run: npm version patch
        - run: git push --tags
      
        
